// ✅ Definición de productos turísticos
const productos = [

{
  ciudad: "Baru E Isla Del Rosario",
  nombre: "4 Islas + Mirador De Barú (Con Plancton)",
  nombreEN: "4 Islands + Barú Viewpoint (With Plancton)",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/2. TOURS ISLAS DEL ROSARIO Y BARU/6. 4 ISLAS + MIRADOR DE BARÚ (CON PLANCTON)",
  totalImagenes: 5,
  precioCOP: 312500,
  ganancia: 0.25,
  descripcion: "Explora cuatro islas paradisíacas y contempla Barú desde las alturas. Cierra el día con un baño mágico entre luces naturales.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling, Visita al planton, Bar abierto dentro del bote",
  destacados: "Tour panorámico, Mirador de barú, Experiencia nocturna con plancton.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Cartagena 360°: Sol, Bahía y Fiesta",
  nombreEN: "Cartagena 360°: Sun, Bay and Party",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/0. PAQUETE/1. CARTAGENA 360",
  totalImagenes: 8,
  precioCOP: 150000,
  descripcion: "🌊 Costa Azul: Sumérgete en la magia de aguas cristalinas y un paisaje costero que enamora. La brisa fresca y el entorno natural te invitan a relajarte y disfrutar de un día frente al mar. ⛵ Tour Bahía en Bote – Tarde y Noche: Navega por la bahía de Cartagena desde el atardecer hasta la noche. Contempla cómo el sol se despide con tonos dorados y vive la magia de la ciudad iluminada desde el agua, una vista que nunca olvidarás. 🎶 Discoteca en la Ciudad: Cierra tu día con la energía vibrante de la vida nocturna cartagenera. Música, luces y un ambiente festivo único harán que la diversión no tenga fin.",
  incluye: "Transporte maritimo ida y vuelta, Almuerzo, Recorrido por la bahia, transporte hacia discoteca.",
  destacados: "Aguas cristalinas, Arena blanca, Instalaciones semiprivadas, Vista del atardecer, Coctel, Musica",
  restringidos: "Menores de edad, Mascotas",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Playa Blanca (Traslado Terrestre)",
  nombreEN: "Playa Blanca (Ground Transfer)",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/1. BARU/1. PLAYA BLANCA X TIERRA CON ALMUERZO",
  totalImagenes: 6,
  precioCOP: 87500,
  descripcion: "Escápate al paraíso con arena blanca y aguas cristalinas. Incluye traslado cómodo y un delicioso almuerzo frente al mar.",
  incluye: "Transporte terrestre, Guía personalizado, Almuerzo",
  destacados: "Agua cristalina, Arena blanca, Ambiente tropical",
  restringidos: "",
  whatsapp: "+57 3239717041",
},


{
  ciudad: "Cartagena",
  nombre: "Barú Playa Blanca + Islas (Traslado Terrestre)",
  nombreEN: "Barú Playa Blanca + Islands (Ground Transfer)",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/1. BARU/2. BARÚ PLAYA BLANCA + ISLAS X TIERRA",
  totalImagenes: 5,
  precioCOP: 150000,
  descripcion: "Vive lo mejor de Barú: playas de ensueño y rincones escondidos. Un recorrido terrestre que te conecta con la magia del Caribe.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo",
  destacados: "Naturaleza marina, Tranquilidad, Experiencia inmersiva",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Barú Playa Tranquila + Bajo De La Tortuga",
  nombreEN: "Barú Playa Tranquila + Bajo De La Tortuga",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/1. BARU/3. BARÚ PLAYA TRANQUILA + BAJO DE LA TORTUGA",
  totalImagenes: 6,
  precioCOP: 187500,
  descripcion: "Relájate en Playa Tranquila y sumérgete en el místico Bajo de la Tortuga, donde la naturaleza te abraza bajo el agua.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling, Alimento para mapaches.",
  destacados: "Visita a los mapaches, Aguas cristalinas, Ambiente natural.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Mambo Beach",
  nombreEN: "Mambo Beach",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/1. BARU/4. MAMBO BEACH",
  totalImagenes: 10,
  precioCOP: 187500,
  descripcion: "Un rincón bohemio frente al mar, con buena vibra, cócteles tropicales y música que te conecta con el alma del Caribe.",
  incluye: "Transporte terrestre, Guía personalizado, Almuerzo, Recorrido por cartagena, Cóctel de bienvenida, Acceso a las instalaciones",
  destacados: "Ambiente caribeño, Música playera, Diversión juvenil.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},
{
  ciudad: "Baru E Isla Del Rosario",
  nombre: "5 Islas Premium (Open Bar + Plancton)",
  nombreEN: "5 Premium Islands (Open Bar + Planton)",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/2. TOURS ISLAS DEL ROSARIO Y BARU/5. 5 ISLAS PREMIUM (OPEN BAR + PLANCTON)",
  totalImagenes: 7,
  precioCOP: 437500,
  descripcion: "Navega entre cinco joyas del mar with barra libre, atardeceres dorados y un espectáculo nocturno de plancton luminoso.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling, Visita al planton, Bar abierto dentro del bote",
  destacados: "Barra libre, Visita a 5 islas exclusivas, Nado con plancton luminoso.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Cholon Forever",
  nombreEN: "Cholon Forever",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/2. TOURS ISLAS DEL ROSARIO Y BARU/7. CHOLON FOREVER",
  totalImagenes: 5,
  precioCOP: 437500,
  descripcion: "La fiesta nunca termina en Cholon: música, mar, y diversión sin límites en el epicentro del goce isleño.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo",
  destacados: "Fiesta en el agua, Música caribeña, Ambiente rumbero.",
  restringidos: "No ingreso de niños, No mascotas",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Santa Marta, Barranquilla",
  nombre: "City Tour Barranquilla / Santa Marta",
  nombreEN: "Barranquilla / Santa Marta City Tour",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/3. TOUR BARRANQUILLA Y SANTA MARTA/8. CITY TOUR BQUILLA-S.MARTA (BASICO)",
  totalImagenes: 10,
  precioCOP: 350000,
  descripcion: "Descubre el alma de dos ciudades vibrantes: historia, cultura y sabor costeño en cada rincón.",
  incluye: "Transporte terrestre, Guía personalizado, Desayuno, Almuerzo, Parada en los lugares turisticos de cada ciudad",
  destacados: "Cultura caribeña, Historia y monumentos, Gastronomía local.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Barranquilla",
  nombre: "Barranquilla",
  nombreEN: "Barranquilla",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/3. TOUR BARRANQUILLA Y SANTA MARTA/9. BARRANQUILLA VIP",
  totalImagenes: 5,
  precioCOP: 393750,
  descripcion: "La Puerta de Oro de Colombia te espera con su carnaval, arquitectura y alegría sin fin.",
  incluye: "Transporte terrestre, Guía personalizado, Almuerzo, Parada en los lugares turisticos de la ciudad",
  destacados: "Carnaval, Río magdalena, Tradición cultural.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Santa Marta",
  nombre: "Santa Marta",
  nombreEN: "Santa Marta",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/3. TOUR BARRANQUILLA Y SANTA MARTA/10. TOURS A SANTA MARTA",
  totalImagenes: 6,
  precioCOP: 312500,
  descripcion: "Historia colonial, playas legendarias y la Sierra Nevada como telón de fondo. Santa Marta lo tiene todo.",
  incluye: "Transporte terrestre, Guía personalizado, Almuerzo, Parada en los lugares turisticos de la ciudad",
  destacados: "Playas naturales, Sierra nevada, Historia colonial.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Archipiélago De San Bernardo",
  nombre: "Santa Cruz El Islote,Tintipan Y Mucura",
  nombreEN: "Santa Cruz El Islote, Tintipan and Mucura",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/4. TOUR ISLA SAN BERNARDO DEL VIENTO Y PLAYA PRIVADA/11. SANTA CRUZ EL ISLOTE,TINTIPAN Y MUCURA (BUS Y LANCHA)",
  totalImagenes: 13,
  precioCOP: 412500,
  descripcion: "Tres islas, tres mundos: cultura, biodiversidad y playas de película. ¡Una travesía inolvidable!",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling.",
  destacados: "Isla más poblada del mundo, Playas paradisíacas, Ambiente isleño auténtico.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Archipiélago De San Bernardo",
  nombre: "Isla Palma",
  nombreEN: "Palma Island",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/4. TOUR ISLA SAN BERNARDO DEL VIENTO Y PLAYA PRIVADA/12. ISLA PALMA  (DIRECTO)",
  totalImagenes: 5,
  precioCOP: 537500,
  descripcion: "Un oasis privado donde la tranquilidad y el lujo se encuentran. Ideal para desconectar y reconectar.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling.",
  destacados: "Exclusividad, Naturaleza tropical, Relax frente al mar.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "San Basilio De Palenque",
  nombre: "San Basilio De Palenque",
  nombreEN: "San Basilio de Palenque",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/4. TOUR ISLA SAN BERNARDO DEL VIENTO Y PLAYA PRIVADA/13. SAN BASILIO DE PALENQUE",
  totalImagenes: 7,
  precioCOP: 437500,
  descripcion: "Sumérgete en la raíz africana de Colombia. Palenque es resistencia, cultura y orgullo ancestral.",
  incluye: "Transporte terrestre, Guía personalizado, Almuerzo.",
  destacados: "Patrimonio cultural de la humanidad, Música y danza afro, Historia viva.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Mantas Beach",
  nombreEN: "Mantas Beach",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/14. MANTAS BEACH",
  totalImagenes: 5,
  precioCOP: 412500,
  descripcion: "Arena suave, brisa cálida y un ambiente relajado. Mantas Beach es tu escape perfecto.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling.",
  destacados: "Playa tranquila, Ambiente familiar, Aguas cristalinas.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Barú",
  nombre: "Sabai",
  nombreEN: "Sabai",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/15. SABAI (MARITIMO Y TERRESTRE)",
  totalImagenes: 6,
  precioCOP: 550000,
  descripcion: "Un beach club con estilo, sabor y ritmo. Sabai vibra con energía caribeña y momentos inolvidables.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling.",
  destacados: "Atardeceres mágicos, Ambiente lounge, Coctelería premium.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Sol Y Papaya ( VIP + Open Bar)",
  nombreEN: "Sol y Papaya (VIP + Open Bar)",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/16. SOL Y PAPAYA ( VIP + OPEN BAR)",
  totalImagenes: 7,
  precioCOP: 437500,
  descripcion: "Sol ardiente, papaya fresca y barra libre. Vive el Caribe con estilo VIP y sabor tropical.",
  incluye: "Transporte acuático, Guía personalizado, Almuerzo, Cóctel de bienvenida, Acceso a las instalaciones, Postre, Servicio de toallas",
  destacados: "Servicio vip, Barra libre, Ambiente tropical.",
  restringidos: "No ingreso de niños",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Cocotera (Bar Experience)",
  nombreEN: "Cocotera (Bar Experience)",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/17. COCOTERA ( BAR EXPERIENCE)",
  totalImagenes: 6,
  precioCOP: 487500,
  descripcion: "Sumérgete en una experiencia sensorial con cócteles exóticos, música envolvente y vistas al mar.",
  incluye: "Transporte terrestre, Transporte acuatico, Guía personalizado, Almuerzo, Snorkeling, Barra libre.",
  destacados: "Experiencia de bar en playa, Cócteles creativos, Música en vivo.",
  restringidos: "No ingreso de niños",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Paue Beach Club",
  nombreEN: "Paue Beach Club",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/18. PAUE BEACH CLUB",
  totalImagenes: 5,
  precioCOP: 550000,
  descripcion: "Elegancia frente al mar, gastronomía de autor y una atmósfera chill para los que buscan lo mejor.",
  incluye: "Transporte acuático, Hidratación, Almuerzo, Cóctel de bienvenida, Acceso a las instalaciones, Postre, Servicio de toallas, Paddle board, Kayak",
  destacados: "Club exclusivo, Camas de playa, Ambiente juvenil y festivo.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Lizamar",
  nombreEN: "Lizamar",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/19. LIZAMAR",
  totalImagenes: 8,
  precioCOP: 437500,
  descripcion: "Tradición isleña y diversión familiar. Lizamar es el corazón cálido de las islas.",
  incluye: "Transporte acuático, Guía personalizado, Almuerzo, Cóctel de bienvenida, Acceso a las instalaciones",
  destacados: "Piscinas naturales, Ambiente familiar, Actividades acuáticas.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Luxury Ambiente VIP",
  nombreEN: "Luxury VIP Ambience",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/20. LUXURY AMBIENTE VIP",
  totalImagenes: 10,
  precioCOP: 587500,
  descripcion: "Exclusividad, confort y servicio premium en un entorno natural que te hará sentir como realeza.",
  incluye: "Transporte acuático, Guía personalizado, Almuerzo, Barra libre (bebidas), Acceso a las instalaciones, Dj, Recorrido isla",
  destacados: "Exclusividad, Servicio premium, Ambiente sofisticado.",
  restringidos: "No ingreso de niños",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Bora Bora Area VIP",
  nombreEN: "Bora Bora VIP Area",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/21. BORA BORA AREA VIP",
  totalImagenes: 10,
  precioCOP: 587500,
  descripcion: "Vive el glamour caribeño en Bora Bora: camas frente al mar, atención personalizada y ambiente de lujo.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Zona exclusiva, Música electrónica, Ambiente cosmopolita.",
  restringidos: "No ingreso de niños",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Pao Pao",
  nombreEN: "Pao Pao",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/22. PAO PAO",
  totalImagenes: 6,
  precioCOP: 462500,
  descripcion: "Ritmo, sabor y mar. Pao Pao es el lugar donde la fiesta y la relajación se encuentran.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Playa estilo boutique, Ambiente lounge, Coctelería fresca.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Ibbiza",
  nombreEN: "Ibbiza",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/23. IBBIZA",
  totalImagenes: 5,
  precioCOP: 450000,
  descripcion: "Inspirado en la famosa isla europea, Ibbiza te ofrece fiesta, estilo y mar en un solo lugar.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Inspiración mediterránea, Música vibrante, Ambiente festivo.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Cocoliso Day Tour Premium",
  nombreEN: "Cocoliso Premium Day Tour",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/24. COCOLISO DAY TOUR PREMIUM",
  totalImagenes: 6,
  precioCOP: 500000,
  descripcion: "Un día completo de placer en Cocoliso: playas, gastronomía y actividades para todos los gustos.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Piscinas naturales, Comodidad premium, Ambiente relajante.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Barú",
  nombre: "Isla Del Encanto Day Tour Premiun Agua",
  nombreEN: "Isla Del Encanto Premium Day Tour Agua",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/25. ISLA DEL ENCANTO DAY TOUR PREMIUN AGUA",
  totalImagenes: 6,
  precioCOP: 512500,
  descripcion: "Navega hacia el Encanto y descubre un mundo de aguas turquesas, sabores caribeños y momentos únicos.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Instalaciones exclusivas, Acceso a playa privada, Almuerzo premium.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Mangata",
  nombreEN: "Mangata",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/26. MANGATA",
  totalImagenes: 6,
  precioCOP: 500000,
  descripcion: "Un refugio natural donde el mar y la selva se abrazan. Mangata es paz, belleza y conexión.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Playa boutique, Diseño único, Ambiente relajado.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Capri Beach Club",
  nombreEN: "Capri Beach Club",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/27. CAPRI BEACH CLUB",
  totalImagenes: 6,
  precioCOP: 575000,
  descripcion: "Estilo mediterráneo en el Caribe colombiano. Capri es sofisticación, sol y buena vida.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Club playero, Ambiente juvenil, Música y cocteles.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Isla Del Pirata Premiun (Barra Libre)",
  nombreEN: "Pirata Island Premium (Open Bar)",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/28. ISLA DEL PIRATA  PREMIUN  (BARRA LIBRE)",
  totalImagenes: 5,
  precioCOP: 525000,
  descripcion: "Vive la leyenda del Caribe con barra libre, música y paisajes que parecen sacados de un cuento.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Fiesta isleña, Barra libre, Ambiente caribeño.",
  restringidos: "No ingreso de niños",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "Encantada Beach",
  nombreEN: "Encantada Beach",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/5. PLAYAS PRIVADAS DE ISLAS DEL ROSARIO Y BARU/29. ENCANTADA BEACH",
  totalImagenes: 8,
  precioCOP: 312500,
  descripcion: "Una playa que hace honor a su nombre: Encantada por su belleza, tranquilidad y energía única.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Tranquilidad, Aguas claras, Ambiente romántico.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Islas Del Rosario",
  nombre: "3 Islas Privadas + Plancton",
  nombreEN: "3 Private Islands + Plankton",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/6. TOUR PLAYAS PRIVADAS EN ISLAS DEL ROSARIO/30. 3 ISLAS PRIVADAS PLANCTON",
  totalImagenes: 8,
  precioCOP: 500000,
  descripcion: "Tres islas solo para ti y un espectáculo nocturno de luces naturales. Una experiencia exclusiva y mágica.",
  incluye: "Transporte terrestre, Transporte acuático, Guía personalizado, Almuerzo, Acceso a las instalaciones",
  destacados: "Exclusividad en islas privadas, Playas paradisíacas, Nado con plancton luminoso.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Atardecer Sibarita Master",
  nombreEN: "Sybarita Master Sunset",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/7. TOURS POR LA BAHIA/31. ATARDECER SIBARITA MASTER",
  totalImagenes: 5,
  precioCOP: 200000,
  descripcion: "Navega al atardecer con estilo sibarita: vino, música suave y vistas que te roban el aliento.",
  incluye: "Navegación de 2 horas, Copa de bienvenida (vino o champaña), Dj en vivo o música lounge, Seguro y tripulación.",
  destacados: "Atardecer inolvidable, Ambiente romántico, Servicio de lujo.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Tour Bahia Barco Bequia",
  nombreEN: "Bequia Bay Boat Tour",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/7. TOURS POR LA BAHIA/32. TOUR BAHIA  BARCO BEQUIA",
  totalImagenes: 4,
  precioCOP: 150000,
  descripcion: "Un paseo elegante por la bahía en el Bequia, con vistas panorámicas y ambiente relajado.",
  incluye: "Transporte marítimo ida y regreso, Guía acompañante, Hidratación, Seguro de viaje.",
  destacados: "Recorrido panorámico, Velocidad y aventura, Paisajes caribeños.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Tour Bahia Barco Phanton",
  nombreEN: "Phanton Bay Boat Tour",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/7. TOURS POR LA BAHIA/33. TOUR BAHIA BARCO PHANTON",
  totalImagenes: 6,
  precioCOP: 150000,
  descripcion: "Vive la bahía con un toque de misterio y sofisticación a bordo del Phanton.",
  incluye: "Transporte marítimo, Frutas tropicales, Bebida refrescante, Seguro.",
  destacados: "Vista de la bahía iluminada, Ambiente festivo, Música y diversión.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Tour Bahia En Bote Tarde Y Noche",
  nombreEN: "Afternoon and Evening Boat Tour",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/7. TOURS POR LA BAHIA/34. TOUR BAHIA EN BOTE TARDE Y NOCHE",
  totalImagenes: 6,
  precioCOP: 100000,
  descripcion: "Desde el sol dorado hasta las luces de la noche, este tour te muestra la bahía en todas sus facetas.",
  incluye: "Paseo marítimo, 1 bebida incluida, Animación a bordo, Seguro.",
  destacados: "Vista de la bahía iluminada, Ambiente festivo, Música y diversión.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Tour Bahia Yate",
  nombreEN: "Yacht Bay Tour",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/7. TOURS POR LA BAHIA/35. TOUR BAHIA YATE",
  totalImagenes: 5,
  precioCOP: 125000,
  descripcion: "Lujo flotante, brisa marina y vistas de postal. El yate te lleva a una experiencia inolvidable.",
  incluye: "Tripulación profesional, Combustible, Hielera con hielo, Equipo de sonido, Seguro.",
  destacados: "Exclusividad, Comodidad premium, Experiencia privada",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Tour Bahia Catamaran",
  nombreEN: "Catamaran Bay Tour",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/7. TOURS POR LA BAHIA/36. TOUR BAHIA CATAMARAN",
  totalImagenes: 5,
  precioCOP: 150000,
  descripcion: "Navega con estilo en un catamarán espacioso, ideal para grupos y momentos especiales.",
  incluye: "Open bar (cerveza, Ron, Cócteles), Snacks, Seguro y tripulación.",
  destacados: "Navegación amplia y cómoda, Open bar, Ambiente social.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Tour Bahia Barco Carroucel (Barra Libre)",
  nombreEN: "Carroucel Bay Boat Tour (Open Bar)",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/7. TOURS POR LA BAHIA/37. TOUR BAHIA BARCO CARROUCEL (BARRA LIBRE)",
  totalImagenes: 4,
  precioCOP: 162500,
  descripcion: "Fiesta flotante con barra libre, música y vistas espectaculares. ¡El Caribe en su máxima expresión!",
  incluye: "Open bar ilimitado, Música a bordo, Animación, Seguro.",
  destacados: "Barra libre, Música y animación, Fiesta en el agua.",
  restringidos: "No ingreso de niños",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Fenix Cena",
  nombreEN: "Fenix Dinner",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/38. FENIX CENA",
  totalImagenes: 5,
  precioCOP: 306250,
  descripcion: "Cena romántica sobre el agua, con el Fénix como anfitrión y el cielo estrellado como testigo.",
  incluye: "Transporte marítimo, Cena de 3 tiempos, Cóctel de bienvenida, Acceso al club, Seguro.",
  destacados: "Cena gourmet, Ambiente exclusivo, Vistas frente al mar.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Day Tour Palmarito",
  nombreEN: "Palmarito Day Tour",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/39. DAY TOUR PALMARITO",
  totalImagenes: 5,
  precioCOP: 262500,
  descripcion: "Un día completo de sol, mar y sabor en Palmarito. Ideal para desconectar y disfrutar.",
  incluye: "Transporte marítimo, Almuerzo típico, Carpa o cama de playa, Bebida refrescante, Seguro.",
  destacados: "Playas privadas, Tranquilidad, Almuerzo típico caribeño.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Ancestral Loungue",
  nombreEN: "Ancestral Lounge",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/40. ANCESTRAL LOUNGUE",
  totalImagenes: 5,
  precioCOP: 250000,
  descripcion: "Un espacio que honra las raíces con música, gastronomía y ambiente espiritual.",
  incluye: "Cóctel de bienvenida, Acceso a zonas vip, Música en vivo o dj, Seguro.",
  destacados: "Agua cristalina, Arena blanca, Ambiente tropical",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Cool Beach Playa Linda",
  nombreEN: "Cool Beach Playa Linda",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/41. COOL BEACH PLAYA LINDA",
  totalImagenes: 5,
  precioCOP: 150000,
  descripcion: "Playa Linda te espera con su arena suave, mar tranquilo y ambiente fresco.",
  incluye: "Transporte marítimo, Almuerzo típico, Bebida refrescante, Carpa o tumbona, Seguro.",
  destacados: "Ambiente juvenil, Playa fresca, Música y relax.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Margarita Beach",
  nombreEN: "Margarita Beach",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/42. MARGARITA BEACH",
  totalImagenes: 5,
  precioCOP: 250000,
  descripcion: "Inspiración tropical con sabor a margarita. Relájate y disfruta del sol con estilo.",
  incluye: "Transporte marítimo, Almuerzo, Zona de playa privada, Coctel de bienvenida, Seguro.",
  destacados: "Arena blanca, Aguas cristalinas, Ambiente paradisíaco.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Paraiso Del Sol (Sencilllo)",
  nombreEN: "Paraiso Del Sol (Simple)",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/43. PARAISO DEL SOL ( SENCILLLO)",
  totalImagenes: 4,
  precioCOP: 125000,
  descripcion: "Un rincón sencillo pero encantador, donde el sol y el mar son los protagonistas.",
  incluye: "Transporte marítimo, Almuerzo típico, Carpa sencilla, Seguro.",
  destacados: "Opción económica, Sol y playa, Ambiente relajado.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Costa Azul",
  nombreEN: "Costa Azul",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/44. COSTA AZUL",
  totalImagenes: 5,
  precioCOP: 75000,
  descripcion: "Aguas azules, brisa fresca y un entorno que te invita a quedarte para siempre.",
  incluye: "Transporte marítimo, Almuerzo, Bebida refrescante, Carpa o cama de playa, Seguro.",
  destacados: "Aguas cristalinas, Tranquilidad, Paisajes caribeños.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Punta Arena (Estandar)",
  nombreEN: "Punta Arena (Standard)",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/8. ISLA DE TIERRA BOMBA  (PUNTA ARENA)/45. PUNTA ARENA (ESTANDAR)",
  totalImagenes: 5,
  precioCOP: 131250,
  descripcion: "Una opción accesible para disfrutar de la playa sin complicaciones. Sol, arena y mar garantizados.",
  incluye: "Transporte marítimo, Almuerzo típico, Bebida refrescante, Carpa o tumbona, Seguro.",
  destacados: "Playa amplia, Servicios completos, Cercanía a cartagena.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "City Tour Chiva",
  nombreEN: "Chiva City Tour",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/9. CITY TOUR CHIVA RUMBERA Y BUS PARTY/46. CITY TOUR CHIVA",
  totalImagenes: 5,
  precioCOP: 112500,
  descripcion: "Súbete a la chiva y recorre la ciudad al ritmo de la música, con alegría y sabor costeño.",
  incluye: "Transporte terrestre, Guía turístico, Paradas en sitios emblemáticos, Animación musical, Seguro.",
  destacados: "Cultura cartagenera, Música típica, Recorrido histórico.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Bus Party",
  nombreEN: "Bus Party",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/9. CITY TOUR CHIVA RUMBERA Y BUS PARTY/47. BUS PARTY",
  totalImagenes: 5,
  precioCOP: 75000,
  descripcion: "¡La rumba sobre ruedas! Música, luces y diversión mientras recorres la ciudad.",
  incluye: "Animador, Dj o música en vivo, Recorrido panorámico, Seguro.",
  destacados: "Fiesta sobre ruedas, Open bar, Ambiente juvenil.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Chiva Rumbera",
  nombreEN: "Chiva Rumbera",
  tipo: "Tour",
  carpetaImagenes: "img/AVENTURAS/9. CITY TOUR CHIVA RUMBERA Y BUS PARTY/48. CHIVA RUMBERA",
  totalImagenes: 5,
  precioCOP: 50000,
  descripcion: "La fiesta más auténtica de Colombia: tambores, baile y tradición en movimiento.",
  incluye: "Animador, Dj o música en vivo, Recorrido panorámico, Seguro.",
  destacados: "Tradición cartagenera, Música en vivo, Diversión nocturna.",
  restringidos: "",
  whatsapp: "+57 3239717041",
},

{
  ciudad: "Cartagena",
  nombre: "Wala Pasadia Beach Club",
  nombreEN: "Wala Pasadia Beach Club",
  tipo: "Pasadía",
  carpetaImagenes: "img/AVENTURAS/9. CITY TOUR CHIVA RUMBERA Y BUS PARTY/49. WALA PASADIA BEACH CLUB",
  totalImagenes: 7,
  precioCOP: 362500,
  descripcion: "Wala es energía, sabor y diversión. Un pasadía que combina relax y fiesta en perfecta armonía.",
  incluye: "Transporte marítimo, Almuerzo tipo gourmet, Coctel de bienvenida, Cama de playa, Seguro.",
  destacados: "Exclusividad, Ambiente caribeño, Servicio premium.",
  restringidos: "No ingreso de niños",
  whatsapp: "+57 3239717041",
},
];

// Exportar para que otros scripts lo usen
window.productos = productos;